/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPackage;

import java.io.*;
import javax.swing.*;
import ClassPackage.UserClass;

/**
 *
 * @author GD Hiruna
 */
public class AdminDashboard extends javax.swing.JFrame {


    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Admin - Colombo institute of Studies");
    }

    AdminDashboard(String userType) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageAcc = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        type = new javax.swing.JComboBox();
        txttype = new javax.swing.JLabel();
        cpass = new javax.swing.JTextField();
        txtcpass = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        txtpass = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        txtusername = new javax.swing.JLabel();
        txtmain2 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageAcc.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ManageAcc.setText("MANAGE ACCOUNTS");
        ManageAcc.setToolTipText("");
        ManageAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageAccActionPerformed(evt);
            }
        });
        getContentPane().add(ManageAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 710, 220, 40));

        Logout.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Logout.setText("LOGOUT");
        Logout.setToolTipText("");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 710, 110, 40));

        submit.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        submit.setText("CREATE ACCOUNT");
        submit.setToolTipText("");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 570, 220, 40));

        type.setFont(new java.awt.Font("Arial Black", 0, 17)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "HR Assistant", "HR Manager", "Administrator" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        getContentPane().add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 490, 170, 50));

        txttype.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txttype.setForeground(new java.awt.Color(255, 255, 255));
        txttype.setText("USER TYPE");
        getContentPane().add(txttype, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 460, -1, -1));

        cpass.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cpass.setToolTipText("");
        cpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpassActionPerformed(evt);
            }
        });
        getContentPane().add(cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 310, 50));

        txtcpass.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtcpass.setForeground(new java.awt.Color(255, 255, 255));
        txtcpass.setText("CONFIRM PASSWORD");
        getContentPane().add(txtcpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 360, -1, -1));

        username.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        username.setToolTipText("");
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 310, 50));

        txtpass.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtpass.setForeground(new java.awt.Color(255, 255, 255));
        txtpass.setText("PASSWORD");
        getContentPane().add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, -1, -1));

        pass.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 310, 50));

        txtusername.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtusername.setForeground(new java.awt.Color(255, 255, 255));
        txtusername.setText("USERNAME");
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 160, -1, -1));

        txtmain2.setFont(new java.awt.Font("Arial Black", 0, 37)); // NOI18N
        txtmain2.setForeground(new java.awt.Color(255, 255, 255));
        txtmain2.setText("CREATE ACCOUNT");
        txtmain2.setToolTipText("");
        getContentPane().add(txtmain2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 80, -1, -1));

        exit.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        exit.setText("EXIT");
        exit.setToolTipText("");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 710, 110, 40));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/admin.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passActionPerformed

    private void cpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpassActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

        String Uname = username.getText();
        String Upass = pass.getText();
        String UconfPass = cpass.getText();
        String Utype = type.getSelectedItem().toString();

        if (Uname.equals("") || Upass.equals("") || UconfPass.equals("") || Utype.equals("")) {
            JOptionPane.showMessageDialog(null, "All fields must be filled out. Please provide the required information.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (!(Upass.equals(UconfPass))) {
            JOptionPane.showMessageDialog(null, "Passwords do not match. Please ensure both password entries are the same.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (Upass.length() < 4) {
            JOptionPane.showMessageDialog(null, "Password is too short. Please choose a password with at least 4 characters.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            UserClass user = new UserClass(Uname, Upass, Utype);
            boolean newUserAdded = user.addNewUser();
            if (newUserAdded) {
                JOptionPane.showMessageDialog(null, "Account has been successfully added to the system.");

                username.setText("");
                pass.setText("");
                cpass.setText("");
                type.setSelectedIndex(0);
            } else {
                System.out.println("Something went wrong, Please try again");
            }
        }

    }//GEN-LAST:event_submitActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        Login login = new Login ();
        if(JOptionPane.showConfirmDialog(null, "Confirm if you want to logout",
                "Exit", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
            login.show();
            this.dispose();
        }
    }//GEN-LAST:event_LogoutActionPerformed

    private void ManageAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageAccActionPerformed
        dispose();
        AdminManage manage = new AdminManage();
        manage.show();
    }//GEN-LAST:event_ManageAccActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        JFrame objexit = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(null, "Confirm if you want to exit",
            "Exit", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JButton ManageAcc;
    private javax.swing.JLabel bg;
    private javax.swing.JTextField cpass;
    private javax.swing.JButton exit;
    private javax.swing.JPasswordField pass;
    private javax.swing.JButton submit;
    private javax.swing.JLabel txtcpass;
    private javax.swing.JLabel txtmain2;
    private javax.swing.JLabel txtpass;
    private javax.swing.JLabel txttype;
    private javax.swing.JLabel txtusername;
    private javax.swing.JComboBox type;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
