/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPackage;

import ClassPackage.EmployeeClass;
import java.io.*;
import java.util.List;
import javax.swing.*;

/**
 *
 * @author GD Hiruna
 */
public class EmployeeSearch extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeSearch
     */
    
    private String UserType = "";
    
    public EmployeeSearch() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Employee Management System - Colombo institute of Studies");
    }
    
    public EmployeeSearch(String UserType) {
        this.UserType = UserType;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Employee Management System - Colombo institute of Studies");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtRAccount = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        goback = new javax.swing.JButton();
        exit3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtRAccount.setFont(new java.awt.Font("Arial Black", 0, 37)); // NOI18N
        txtRAccount.setForeground(new java.awt.Color(255, 255, 255));
        txtRAccount.setText("SEARCH EMPLOYEE");
        txtRAccount.setToolTipText("");
        getContentPane().add(txtRAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, -1, -1));

        search.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 140, 110, 40));

        txtSearch.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 550, 40));

        goback.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        goback.setText("BACK");
        goback.setToolTipText("");
        goback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackActionPerformed(evt);
            }
        });
        getContentPane().add(goback, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 710, 110, 40));

        exit3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        exit3.setText("EXIT");
        exit3.setToolTipText("");
        exit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit3ActionPerformed(evt);
            }
        });
        getContentPane().add(exit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 710, 110, 40));

        txtResult.setColumns(20);
        txtResult.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtResult.setRows(5);
        jScrollPane1.setViewportView(txtResult);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 680, 470));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/main.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        String keyword = txtSearch.getText();

        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Keyword cannot be blank",
                    "Login Form", JOptionPane.ERROR_MESSAGE);
        } else {
            EmployeeClass employee = new EmployeeClass(); // calling constructor
            String empTableTitle = "Name\t\tAge\tAddress\t\tEPF\t\tDepartment\tDesignation\n" +
                    "-----------------------------------------------------------------------------------------------------------------\n";

            List<EmployeeClass> matchingEmployees = employee.SearchEmployee(keyword);

            if (!matchingEmployees.isEmpty()) {
                StringBuilder resultText = new StringBuilder(empTableTitle);
                for (EmployeeClass matchingEmployee : matchingEmployees) {
                    resultText.append(matchingEmployee.getName()).append("\t")
                            .append(matchingEmployee.getAge()).append("\t")
                            .append(matchingEmployee.getAddress()).append("\t")
                            .append(matchingEmployee.getEPF()).append("\t\t")
                            .append(matchingEmployee.getDepartment()).append("\t\t")
                            .append(matchingEmployee.getDesignation()).append("\n");
                }
                txtResult.setText(resultText.toString());
            } else {
                JOptionPane.showMessageDialog(null, "Sorry! We do not have any matching Employee",
                        "Search a Employee", JOptionPane.ERROR_MESSAGE);
                txtResult.setText(""); // Clear the txtResult JTextArea if no matching employees found
            }
        }
    }//GEN-LAST:event_searchActionPerformed

    private void gobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobackActionPerformed
        dispose();
        EmployeeDashboard admin = new EmployeeDashboard(UserType);
        admin.show();
    }//GEN-LAST:event_gobackActionPerformed

    private void exit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit3ActionPerformed
        JFrame objexit = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(null, "Confirm if you want to exit",
            "Exit", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_exit3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton exit3;
    private javax.swing.JButton goback;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton search;
    private javax.swing.JLabel txtRAccount;
    private javax.swing.JTextArea txtResult;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
