/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPackage;

import ClassPackage.DepartmentClass;
import java.io.*;
import javax.swing.*;

/**
 *
 * @author GD Hiruna
 */
public class EmployeeRole extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeRole
     */

    private String UserType = "";
    
    public EmployeeRole() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Employee Management System - Colombo institute of Studies");
    }
    
    public EmployeeRole(String UserType) {
        this.UserType = UserType;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Employee Management System - Colombo institute of Studies");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submit = new javax.swing.JButton();
        txtDes = new javax.swing.JTextField();
        Des = new javax.swing.JLabel();
        txtmain3 = new javax.swing.JLabel();
        txtmain2 = new javax.swing.JLabel();
        txtmain4 = new javax.swing.JLabel();
        Dep = new javax.swing.JLabel();
        txtDep = new javax.swing.JTextField();
        goback = new javax.swing.JButton();
        exit3 = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submit.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        submit.setText("SUBMIT");
        submit.setToolTipText("");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 140, 50));

        txtDes.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtDes.setToolTipText("");
        txtDes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDesActionPerformed(evt);
            }
        });
        getContentPane().add(txtDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, 370, 50));

        Des.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Des.setForeground(new java.awt.Color(255, 255, 255));
        Des.setText("DESIGNATION");
        getContentPane().add(Des, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, -1, -1));

        txtmain3.setFont(new java.awt.Font("Arial Black", 0, 37)); // NOI18N
        txtmain3.setForeground(new java.awt.Color(255, 255, 255));
        txtmain3.setToolTipText("");
        getContentPane().add(txtmain3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 420, -1, -1));

        txtmain2.setFont(new java.awt.Font("Arial Black", 0, 37)); // NOI18N
        txtmain2.setForeground(new java.awt.Color(255, 255, 255));
        txtmain2.setText("ADD DEPARTMENT /");
        txtmain2.setToolTipText("");
        getContentPane().add(txtmain2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 60, -1, -1));

        txtmain4.setFont(new java.awt.Font("Arial Black", 0, 37)); // NOI18N
        txtmain4.setForeground(new java.awt.Color(255, 255, 255));
        txtmain4.setText("DESIGNATION");
        txtmain4.setToolTipText("");
        getContentPane().add(txtmain4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, -1, -1));

        Dep.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Dep.setForeground(new java.awt.Color(255, 255, 255));
        Dep.setText("DEPARTMENT");
        getContentPane().add(Dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, -1, -1));

        txtDep.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtDep.setToolTipText("");
        txtDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepActionPerformed(evt);
            }
        });
        getContentPane().add(txtDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 370, 50));

        goback.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        goback.setText("BACK");
        goback.setToolTipText("");
        goback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackActionPerformed(evt);
            }
        });
        getContentPane().add(goback, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 710, 110, 40));

        exit3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        exit3.setText("EXIT");
        exit3.setToolTipText("");
        exit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit3ActionPerformed(evt);
            }
        });
        getContentPane().add(exit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 710, 110, 40));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/main.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        String DepName = txtDep.getText();
        String Designations = txtDes.getText();
        
        DepartmentClass department = new DepartmentClass(DepName, Designations);

        if (DepName.equals("") || Designations.equals("")) {
            JOptionPane.showMessageDialog(null, "All fields must be filled out. Please provide the required information.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if(department.checkDepAndDesAvailability(DepName, Designations) == true) {
            JOptionPane.showMessageDialog(null, "Department and Designation already exists. Duplicate found.", "Error", JOptionPane.ERROR_MESSAGE);
        }else {
            boolean addDepartment = department.addDepartment();
            if (addDepartment) {
                JOptionPane.showMessageDialog(null, "Department and Designation has been successfully added to the system.");
                
                txtDep.setText("");
                txtDes.setText("");
            } else {
                System.out.println("Something went wrong, Please try again");
            }
        }
    }//GEN-LAST:event_submitActionPerformed

    private void txtDesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDesActionPerformed

    private void gobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobackActionPerformed
        dispose();
        EmployeeDashboard admin = new EmployeeDashboard(UserType);
        admin.show();
    }//GEN-LAST:event_gobackActionPerformed

    private void exit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit3ActionPerformed
        JFrame objexit = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(null, "Confirm if you want to exit",
            "Exit", JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_exit3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeRole.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeRole().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dep;
    private javax.swing.JLabel Des;
    private javax.swing.JLabel bg;
    private javax.swing.JButton exit3;
    private javax.swing.JButton goback;
    private javax.swing.JButton submit;
    private javax.swing.JTextField txtDep;
    private javax.swing.JTextField txtDes;
    private javax.swing.JLabel txtmain2;
    private javax.swing.JLabel txtmain3;
    private javax.swing.JLabel txtmain4;
    // End of variables declaration//GEN-END:variables
}
