/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;
import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author GD Hiruna
 */
public class AdminManage extends javax.swing.JFrame {
    File myFile;
    
    /**
     * Creates new form AdminManage
     */
    public AdminManage() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Admin - Colombo institute of Studies");
        
        try{
            myFile = new File("E:\\Java\\Colombo institute of Studies\\src\\data\\accounts.txt");
            if (myFile.createNewFile()){
                System.out.println("File Created: " + myFile.getName());
            }
            else{
                System.out.println("File already exists.");
            }
        }
        catch(IOException ex){
            System.out.println("Error happened when creating file");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txttype = new javax.swing.JLabel();
        type = new javax.swing.JComboBox();
        txtusername = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        cusername = new javax.swing.JTextField();
        txtcusername = new javax.swing.JLabel();
        txtRAccount = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        goback = new javax.swing.JButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txttype.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txttype.setForeground(new java.awt.Color(255, 255, 255));
        txttype.setText("USER TYPE");
        getContentPane().add(txttype, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 490, -1, -1));

        type.setFont(new java.awt.Font("Arial Black", 0, 17)); // NOI18N
        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "HR Assistant", "HR Manager", "Administrator" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        getContentPane().add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 520, 170, 50));

        txtusername.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtusername.setForeground(new java.awt.Color(255, 255, 255));
        txtusername.setText("USERNAME");
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 290, -1, -1));

        username.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        username.setToolTipText("");
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 310, 50));

        cusername.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cusername.setToolTipText("");
        cusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusernameActionPerformed(evt);
            }
        });
        getContentPane().add(cusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, 310, 50));

        txtcusername.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtcusername.setForeground(new java.awt.Color(255, 255, 255));
        txtcusername.setText("CONFIRM USERNAME");
        getContentPane().add(txtcusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 390, -1, -1));

        txtRAccount.setFont(new java.awt.Font("Arial Black", 0, 37)); // NOI18N
        txtRAccount.setForeground(new java.awt.Color(255, 255, 255));
        txtRAccount.setText("REMOVE ACCOUNT");
        txtRAccount.setToolTipText("");
        getContentPane().add(txtRAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, -1, -1));

        submit.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        submit.setText("REMOVE ACCOUNT");
        submit.setToolTipText("");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 600, 220, 40));

        goback.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        goback.setText("GO BACk");
        goback.setToolTipText("");
        goback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackActionPerformed(evt);
            }
        });
        getContentPane().add(goback, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 710, 110, 40));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/admin-manage.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try {
            boolean valid = false;
            FileReader fReader = new FileReader(myFile);
            BufferedReader bReader = new BufferedReader(fReader);
            
            String FindLine;
            String uName = username.getText();
            String utype = type.getSelectedItem().toString();
            String UserType, UserName;
            
            if ("Admin".equals(uName) && "Administrator".equals(utype)) {
                JOptionPane.showMessageDialog(
                    null,
                    "Admin accounts cannot be removed.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
                );
                
                return;
                
            }
            
            // Create a temporary file
            File tempFile = new File("tempFile.txt");
            FileWriter fWriter = new FileWriter(tempFile);
            BufferedWriter bWriter = new BufferedWriter(fWriter);
           
            outerLoop:
            while (null != (FindLine = bReader.readLine())) {
                UserName = FindLine.split("---")[0];
                UserType = FindLine.split("---")[2];
                if (uName.equals(UserName) && utype.equals(UserType)) {
                    valid = true;

                    // Skip writing the line to the temporary file
                    JOptionPane.showMessageDialog(null, "Account has been successfully removed from our system. (" + UserName + " - " + UserType + ")", "Account Removed", JOptionPane.INFORMATION_MESSAGE);
                    continue outerLoop; // Skip the rest of the loop and move to the next iteration
                }

                // Write the line to the temporary file
                bWriter.write(FindLine);
                bWriter.newLine();
            }

            if (!valid) {
                JOptionPane.showMessageDialog(null, "You have entered an invalid username or user type.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            // Close readers and writers
            bReader.close();
            fReader.close();
            bWriter.close();
            fWriter.close();

            // Replace the original file with the temporary file
            myFile.delete(); // Delete the original file
            tempFile.renameTo(myFile); // Rename the temporary file to the original file name

        } catch (IOException ex) {
            System.out.println("An Error Occurred Searching " + ex);
        }

    }//GEN-LAST:event_submitActionPerformed

    private void gobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobackActionPerformed
        dispose();
        AdminDashboard admin = new AdminDashboard();
        admin.show();
    }//GEN-LAST:event_gobackActionPerformed

    private void cusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusernameActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JTextField cusername;
    private javax.swing.JButton goback;
    private javax.swing.JButton submit;
    private javax.swing.JLabel txtRAccount;
    private javax.swing.JLabel txtcusername;
    private javax.swing.JLabel txttype;
    private javax.swing.JLabel txtusername;
    private javax.swing.JComboBox type;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
