/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;
import java.io.*;
import javax.swing.JOptionPane;

/**
 *
 * @author GD Hiruna
 */
public class Login extends javax.swing.JFrame {
File myFile;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Login - Colombo institute of Studies");
        
        try{
            myFile = new File("E:\\Java\\Colombo institute of Studies\\src\\data\\accounts.txt");
            if (myFile.createNewFile()){
                System.out.println("File Created: " + myFile.getName());
            }
            else{
                System.out.println("File already exists.");
            }
        }
        catch(IOException ex){
            System.out.println("Error happened when creating file");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submit = new javax.swing.JButton();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        txtpassword = new javax.swing.JLabel();
        txtusername = new javax.swing.JLabel();
        txtlogin = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        submit.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        submit.setText("LOGIN");
        submit.setToolTipText("");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 610, 132, 45));

        username.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        username.setToolTipText("");
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, 310, 50));

        password.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 490, 310, 50));

        txtpassword.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        txtpassword.setText("PASSWORD");
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, -1, -1));

        txtusername.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        txtusername.setForeground(new java.awt.Color(255, 255, 255));
        txtusername.setText("USERNAME");
        getContentPane().add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, -1, -1));

        txtlogin.setFont(new java.awt.Font("Arial Black", 0, 57)); // NOI18N
        txtlogin.setForeground(new java.awt.Color(255, 255, 255));
        txtlogin.setText("LOGIN");
        getContentPane().add(txtlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 190, 210, 90));

        bg.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/login.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try{
            boolean valid= false;          
            FileReader fReader = new FileReader(myFile);
            BufferedReader bReader = new BufferedReader(fReader);
            
            String FindLine;
            String uName = username.getText();
            String uPass = password.getText();
            String UserType,UserName,UserPass;
            outerLoop:
            while(null!= (FindLine = bReader.readLine())){
                UserName = FindLine.split("---")[0];
                UserPass = FindLine.split("---")[1];
                UserType= FindLine.split("---")[2];
                if (UserName.equals(uName) && UserPass.equals(uPass)){
                    valid = true;
                    //break outerLoop;
                    JOptionPane.showMessageDialog(null, "Login Success! Welcome, "+UserType+" ("+UserName+")", "Login Success", JOptionPane.INFORMATION_MESSAGE);
                     if (UserType.equals("Admin")){
                        AdminDashboard obj = new AdminDashboard();
                        obj.show();
                        this.dispose();                    
                     }
                    else{
                        AdminDashboard obj = new AdminDashboard();
                        obj.show();
                        this.dispose();
                    }
                    break;
                }  
            }
            if(!valid){
                    JOptionPane.showMessageDialog(null, "You have entered an invalid username or password.","Error",JOptionPane.ERROR_MESSAGE);
               }
            fReader.close();
            bReader.close();
        }                      
        catch(IOException ex){
            System.out.println("An Error Occured Searching "+ ex);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton submit;
    private javax.swing.JLabel txtlogin;
    private javax.swing.JLabel txtpassword;
    private javax.swing.JLabel txtusername;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
